dist: trusty
language: rust
services: docker
sudo: required
env:
  global:
    # This will be part of the release tarball
    # TODO change the project name
    - CRATE_NAME=lonlat_bng
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64


matrix:
  include:
    # STABLE
    - os: osx
      osx_image: xcode11.3
      rust: stable
      env: TARGET=x86_64-apple-darwin

    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
      services: docker

    # BETA
    - os: osx
      rust: beta
      osx_image: xcode11.3
      env: TARGET=x86_64-apple-darwin

    - os: linux
      rust: beta
      env: TARGET=x86_64-unknown-linux-gnu

    # NIGHTLY
    - os: osx
      osx_image: xcode11.3
      rust: nightly
      env: TARGET=x86_64-apple-darwin

    - os: linux
      rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu

before_install:
  - set -e

install:
  - bash ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - shell_session_update() { :; };
  # - curl -sSL https://rvm.io/mpapis.asc | gpg --import -
  # - rvm get stable
  - bash ci/before_deploy.sh

deploy:
  # TODO Regenerate this api_key for your project, this one won't work for you. Here's how:
  # - Go to 'https://github.com/settings/tokens/new' and generate a Token with only the
  # `public_repo` scope enabled
  # - Call `travis encrypt $github_token` where $github_token is the token you got in the previous
  # step and `travis` is the official Travis CI gem (see https://rubygems.org/gems/travis/)
  # - Enter the "encrypted value" below
  api_key:
        - secure: wDh8EvATheEaSQJaQ+S6HwRv5dh62I+Ji7t0N35pJhGh0wIjMSBzPz+57wox5AFR+FgJVTEm5akmtpxXYqkDSrkXjK9L2ZsjGD5JAJtjzlQvO7i+GCbivSUsKEkqOEcVR/hW5+VZY8U4DaUTI8DupFAGkxNhEwnkNNT9gaodrJBH23J/bnNTt7dpM+rdJIB3ZPdYkytxDm4Rn1JHXi7boU+5rObvb2/NJd6jnRuYZv8CTBlQHErApC0MmR2hqZZmi2M/rexWAD3M5mX0LSoch4C/2v3heA7eIX5GDpu/FvC2nMVLSFZ0etdUv2PCXIrqdX+SL16s3aVTHxwmks1VzmS7/moTdW8azihvrl9wN6bSb18kyvyXd0G3GegeRgeR9W/V9RspUlNOAHe1McD36jL2VYZLazqy5aUKVjtStwxROHCI/0EH69UX/35deMz9N2noDOWQUCoSvBjd9NSGUi1ba4PexJG2DATeSpGqOKcUQu5d6qtGfLrzBzBjc449nCj9D6tfrPAQrhfOx6N2ntguR+RENjXxnmaAhyOiXuaAy/Jtij+tt7zCsXbjYsGI7fXlZAOBORT8p2Vd8yqV1K8iguHNvuLlNInLV4wfyFEa1E2i23HosPZdysSYgr5wyZ7KWt4O4r8YOGn3rQmWtmw9+XeYqIbIwtTzAtX6Ets=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  # don't delete the artifacts from previous phases
  skip_cleanup: true
  # deploy when a new tag is pushed
  on:
    # TODO Here you can pick which targets will generate binary releases
    # In this example, there are some targets that are tested using the stable
    # and nightly channels. This condition makes sure there is only one release
    # for such targets and that's generated using the stable channel
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
