dist: trusty
language: rust
services: docker
sudo: required
env:
  global:
    # This will be part of the release tarball
    # TODO change the project name
    - CRATE_NAME=lonlat_bng
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    # GH_TOKEN
    - secure: FCIbI4NGniodYftwW7yb0vVLHlWkARnKUmmOsKkgCMJVmcmVOD7YWJLWP6ICTTOUubWiljckjv8MVNu61e2+dSWNbG6s2VVAMpUo0052I3yB4Ws8ZOC1eOAbinq5OAFv8ZRVRkowtct77/UAcuj0eVI3V2EMR2VXcOfm1Wnv+loPsjXgf6+b+8UMYS7roluGZ14wVno+5d37YCftDAVPvLYwFudrUIyR55XizmNVjEU7YIVb8373Ae7VzZztPDPW80vJwHHXvA+UGKRwaUyQlYjd1ececNx024/Nd1I0ECkmUhR67jrUHt0gXnCVWm/WasqOMvTzt+hdBq6AeORB/C3YTuQ6i937by61ttOrT9A3jF3oIzZR1j3Sg6Y7/Wd5cHWtTw4bVdDYjpHXBKlSFIq9dFjK5TDd75KaRQNBfcDwWL0od+oLSZ9Z59r4xRqLEPIWWwAKhGPaNDNBlJ8/0qfIxXK++/BbCuSGG8j3AXmVbpmyvNKMf+xHhY+oW1vj42pgG/aMZE3OlfMD3hMp9fti3EFjQScY1/mbDkvN6RknfMfDZuF0AdxUEtwhu2+X0tTZfe6dFsnEBLcqJH0ng5WPo/HRGVrjSc8nbZ7kUb5kkx946Emr1Mka+jRGVA+U3r7JpF62gasEwSZL8kZgvsRhAhJhinagHAeTlyywmhQ=


matrix:
  include:
    # STABLE
    - os: osx
      osx_image: xcode8.3
      rust: stable
      env: TARGET=x86_64-apple-darwin

    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
      services: docker

    # BETA
    - os: osx
      rust: beta
      osx_image: xcode8.3
      env: TARGET=x86_64-apple-darwin

    - os: linux
      rust: beta
      env: TARGET=x86_64-unknown-linux-gnu

    # NIGHTLY
    - os: osx
      osx_image: xcode8.3
      rust: nightly
      env: TARGET=x86_64-apple-darwin

    - os: linux
      rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu

before_install:
  - set -e

install:
  - bash ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  # OSX deploy doesn't need a Dockerised manylinux1 build
  - if ! [[ "$TARGET" == "x86_64-unknown-linux-gnu" ]]; then bash ci/before_deploy.sh; fi
  # Linux deploy needs Dockerised manylinux1 artefacts
  - if [[ "$TARGET" == "x86_64-unknown-linux-gnu" ]]; then docker pull $DOCKER_IMAGE; fi
  - if [[ "$TARGET" == "x86_64-unknown-linux-gnu" ]]; then sudo docker run -e TRAVIS_TAG="$TRAVIS_TAG" --rm -v `pwd`:/io $DOCKER_IMAGE /io/ci/manylinux_rust.sh; fi

deploy:
  # TODO Regenerate this api_key for your project, this one won't work for you. Here's how:
  # - Go to 'https://github.com/settings/tokens/new' and generate a Token with only the
  # `public_repo` scope enabled
  # - Call `travis encrypt $github_token` where $github_token is the token you got in the previous
  # step and `travis` is the official Travis CI gem (see https://rubygems.org/gems/travis/)
  # - Enter the "encrypted value" below
  api_key:
        - secure: DTWgwQjhzyIMwvdv6Sy+sLh0FoBOczxmRUO7wrBeahYK+wIz7ZfDkFp4j1pEeQYgHtB6hxEaYSKojNxHHvqCWkM5WtDm/cdU9tGkyVsTHsh54DQGyardiV704eiIWkFtFrCSKYHcJ/CMuTTwmbNIZZG281puJoHhtAoutTAPXrFzYtAC2zYWx+cODs9UXbq3yus6UBQJ8srHTYbKJDUQYGSDpXI0QSKj5O9CUzrmd11sZ6ol7+Xjykv6me2YjHKX9NnxYfplVLnEgDHZeAD8GKIYpb8Lb0AgKtkZh4EU+hC/9+5bqFQukeSVczEnTQKkHOyM36rbqnXJz9U7ar4JTYLaRIz5Uawcn4Mk2gStx3V+8TvzOd4rGpdRhFPVSiZzS+nwvTgmSowuo2bY/x8nXVEP2BqBUp98I4H36GtAk+xmRTl8ORmg+TytQJUGgnN1cmT0NAaGLdqfNUJ+eNBHP+hc0lLDelaYlEEOMq4G3NyTrYHgrDCcm9dmvB2znZLJGvVOZqLkH90DRxIpQ6VSFnt2n59oa2fKas6gjeWpsMY3OwrBj5lSe7yWM4cZvSmoBHQO1kAr13HrP8y/opFV+HeXWva9hwWSWAo8W7Lib8XXC+uBYwKPfO83QP2N+mr6gwdjgd5HTAMmmnAoRjOrcGlNIk3HfAXClGNcz3sLk3I=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  # don't delete the artifacts from previous phases
  skip_cleanup: true
  # deploy when a new tag is pushed
  on:
    # TODO Here you can pick which targets will generate binary releases
    # In this example, there are some targets that are tested using the stable
    # and nightly channels. This condition makes sure there is only one release
    # for such targets and that's generated using the stable channel
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
