[package]
name = "lonlat_bng"
description = "Convert longitude and latitude coordinates to BNG coordinates, and vice versa"
version = "0.6.7"
authors = ["Stephan Hügel <urschrei@gmail.com>"]
license = "MIT"
keywords = ["OSGB36", "Geo", "FFI", "ETRS89", "OSTN02"]
repository = "https://github.com/urschrei/lonlat_bng"
documentation = "https://urschrei.github.io/lonlat_bng/"
readme = "README.md"
edition = "2018"
build = "src/build.rs"

[build-dependencies]
cbindgen = "0.13.1"

[dependencies]
libc = "0.2.67"
rand = "0.7.3"
ostn15_phf = { git = "https://github.com/urschrei/ostn15_phf.git" }
rayon = "1.3.0"

[lib]
name = "lonlat_bng"
crate-type = ["rlib", "cdylib"]
test = true
doctest = false
doc = true

[profile.release]
rpath = true
lto = true
codegen-units = 1
[profile.bench]
lto = true
codegen-units = 1
